language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: GDK61faa58gSoS7fYSTCKWNz/8BhPBavqmZ8EbSwXAK/u7hiCDbsDj/XZOioNy2l4501ZXqFk86ZYt5q2hvKj75KHiEqmw4x+a2mw8LvylnKaLpNNPt9diXM8K6sGXqVXF3xdM1p0s1W4lVY9hR/qVXM7JW1sVpiHwwHvhIazBG8xMutuiOX/uRmBwxuXGiNjbP4IShpl1RvTiuZCG4A6N4w9t9QZG2lZ3ia55zq4hWiim6DhnjqHWrX0hCk0qWkj6uR2mI3DIA/KFwXXKfrhJufvww+pBdzuTE5pMZxA8QjKFWNmpsTfldbn7NA2gt27XtmdWg5Xk9jZWybRHrIHuEMQtjXYOHXsibaCe5NkPA8OvNBalyXOHHkCFRoKQ8Lgae+s3+Nv+/Qc0cxrbqsAuEqJiMZaHjYMhBwxQ841+FuLIkX7LpXFhsoRx3M+FEJMF2D7Ha8pmzzWAOs1XpSJrONEgZ6YFTFGH8nNwmboBDMkbjykoRoPPeCQ7ZzQ52ARE2qkDX76M/dre9TGq1hzrVK2tX7DOOzwZe2C8Fy+aFlioZ+MonlgiXbvsQ0IM7mM0SFzD7EKwBkyhagX3B/WtMG+pDMzLIJ/76yi0RIHgsnstzSWWux3jSh5qoOb0/q89CFYsUBFTpS2Z1kysH8ye7xrI0qnMsRe3FZSpwFRqY=
